### ISSUE TITLE
Conjure seems to now fail silently if the IR definition is invalid

### ISSUE THREAD

**Issue by j-baker** [palantir/gradle-conjure#569]
I don't know whether you'd like to class this as a gradle-conjure issue or a conjure-java issue.

If your conjure definition is invalid (in my case, I changed it from):

```yaml
MyType:
  fields:
    existing: string
```

to

```yaml
NewType:
  alias: int

MyType:
  fields:
    existing: string
    newField: optional<NewType>
```

This is invalid because it's integer, not int. But the IR compilation does not error and instead produces no output (the output IR folder is empty). This then causes conjureJava to no-op, since it now has no source (gradle skips the task). It also does not clear out previously generated files.

I think that in the past, Conjure-java used to fail if the file did not exist. Additionally conjure used to hard fail if it wasn't going to produce any output.
